FROM node:18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install -g turbo

RUN npm install -g next

RUN turbo run build --filter on-boarding

EXPOSE 3003

CMD turbo run start --filter on-boarding