FROM node:18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install -g turbo

RUN npm install -g next

RUN turbo run build --filter performance

EXPOSE 3001

CMD turbo run start --filter performance