FROM node:18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install -g turbo

RUN npm install -g next

RUN turbo run build --filter sso-admin

EXPOSE 3000

CMD turbo run start --filter sso-admin