FROM node:18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install -g turbo

RUN npm install -g next

RUN turbo run build --filter recruiting

EXPOSE 3002

CMD turbo run start --filter recruiting