export const USERS = "USERS";
export const HIRING_TEAM = "HIRING_TEAM";
export const FORM_TABLE = "FORM_TABLE";
export const ADD_JOB_INFO = "ADD_JOB_INFO";
export const REFERRAL_LIST = "REFERRAL_LIST";
export const INTERVIEW_PLAN = "INTERVIEW_PLAN";
export const EXISTING_JOB = "EXISTING_JOB";
export const OPENINGS_APPROVALS_DETAILS = "APPROVALS_DETAILS";
export const JOB_INFORMATION_APPROVALS = "JOB_INFORMATION_APPROVALS";
export const VIEW_JOB_MAIN = "VIEW-JOBS-MAIN";
export const TASKS = "TASKS";
export const SCORE_CARD = "SCORE_CARD";
export const REFERRAL_DETAILS = "REFERRAL_DETAILS";
export const JOB_OVERVIEW = "JOB_OVERVIEW";
export const FEEDBACK_DETAILS = "FEEDBACK_DETAILS";
export const JOB_DETAILS = "JOB_DETAILS";
export const SAMPLE_JOB = "SAMPLE_JOB";
export const JOB_OPENING_INFO_IN_JOB_DETAILS =
  "JOB_OPENING_INFO_IN_JOB_DETAILS";
export const SINGLE_JOB_OPENING_INFO = "SINGLE_JOB_OPENING_INFO";
export const UPDATE_JOB_APPROVAL = "UPDATE_JOB_APPROVAL";
export const JOB_SETUP_SCORE_CARD = "JOB_SETUP_SCORE_CARD";
export const STAGE_TRANSITION = "STAGE_TRANSITION";
export const PRIVATE_NOTE = "PRIVATE_NOTE";
export const ADD_AS_PROSPECT_TO = "ADD_AS_PROSPECT_TO";
export const OVER_ALL_RECOMMENDATIONS = "OVER_ALL_RECOMMENDATIONS";
export const CANDIDATE_MAIN = "CANDIDATE_MAIN";
export const CONFIGURE_POOL = "CONFIGURE_POOL";
export const CANDIDATE_JOBS = "CANDIDATE_JOBS";
export const GET_JOB_CANDIDATES = "GET_JOB_CANDIDATES";
export const APPLICATION_CANDIDATE = "APPLICATION_CANDIDATE";
export const JOB_POST = "JOB_POST";
export const PIPELINE = "PIPELINE";
export const CANDIDATE_PROSPECT = "CANDIDATE_PROSPECT";
export const EVENT = "EVENT";
export const SCHEDULE_INTERVIEW = "SCHEDULE_INTERVIEW";
export const EMAIL_TEMPLATES = "EMAIL_TEMPLATES";
export const MANAGE_JOBS_FIELDS = "MANAGE_JOBS_FIELDS";
export const MANAGE_INTERVIEWER_TAGS = "MANAGE_INTERVIEWER_TAGS";
export const CLOSE_REASON_FOR_JOB = "CLOSE_REASON_FOR_JOB";
export const CANDIDATE_TAGS = "CANDIDATE_TAGS";
export const MANAGE_USER_FIELDS = "MANAGE_USER_FIELDS";
export const REJECTED_REASONS = "REJECTED_REASONS";
export const OFFICE_API = "OFFICE_API";
export const DEPARTMENT_API = "DEPARTMENT_API";
export const OFFER_TEMPLATE = "OFFER_TEMPLATE";
export const OFFER_DETAILS = "OFFER_DETAILS";
export const JOB_OPENINGS = "JOB_OPENINGS";
export const JOB_BOARDS = "JOB_BOARDS";
export const EFFICIENCY_REPORTS = "EFFICIENCY_REPORTS";
export const PIPELINE_REPORTS = "PIPELINE_REPORTS";
export const JOB_CANDIDATE = "JOB_CANDIDATE";
export const OVERVIEW_SAVED_REPORTS = "OVERVIEW_SAVED_REPORTS";
export const JOB_DASHBOARD = "JOB_DASHBOARD";
export const ACTIVITY_FEED = "ACTIVITY_FEED";
export const OFFER_HIRING = "OFFER_HIRING";
export const DASHBOARD = "DASHBOARD";
export const SCORE_CARD_DETAILS = "SCORE_CARD_DETAILS";
export const NOTIFICATIONS = "NOTIFICATIONS";
export const NOTIFICATIONS_BY_USER = "NOTIFICATIONS_BY_USER";
export const ESSENTIAL_REPORTS = "ESSENTIAL_REPORTS";
export const PERSONALIZED_DASHBOARD = "PERSONALIZED_DASHBOARD";
export const PIPE_LINE_REPORTS = "PIPE_LINE_REPORTS";
export const INTERVIEWING_ACTIVITY = "INTERVIEWING_ACTIVITY";
export const DEPARTMENT_SUMMARY = "DEPARTMENT_SUMMARY";
export const APPLICATION_OVER_TIME = "APPLICATION_OVER_TIME";
export const CANDIDATE_SOURCE = "CANDIDATE_SOURCE";
export const USER_API = "USER-API";
export const NOTIFICATIONS_ACCOUNT = "NOTIFICATIONS_ACCOUNT";
export const JOB_ACTIVITY_FEED = "JOB_ACTIVITY_FEED";

export const TAGS = [
  EVENT,
  USERS,
  ADD_JOB_INFO,
  EXISTING_JOB,
  INTERVIEW_PLAN,
  OPENINGS_APPROVALS_DETAILS,
  JOB_INFORMATION_APPROVALS,
  HIRING_TEAM,
  REFERRAL_LIST,
  TASKS,
  FORM_TABLE,
  SCORE_CARD,
  VIEW_JOB_MAIN,
  REFERRAL_DETAILS,
  JOB_OVERVIEW,
  FEEDBACK_DETAILS,
  JOB_OPENING_INFO_IN_JOB_DETAILS,
  JOB_DETAILS,
  SAMPLE_JOB,
  UPDATE_JOB_APPROVAL,
  JOB_SETUP_SCORE_CARD,
  STAGE_TRANSITION,
  PRIVATE_NOTE,
  ADD_AS_PROSPECT_TO,
  OVER_ALL_RECOMMENDATIONS,
  CANDIDATE_MAIN,
  CONFIGURE_POOL,
  CANDIDATE_JOBS,
  GET_JOB_CANDIDATES,
  CANDIDATE_MAIN,
  CONFIGURE_POOL,
  APPLICATION_CANDIDATE,
  JOB_POST,
  MANAGE_JOBS_FIELDS,
  MANAGE_INTERVIEWER_TAGS,
  CLOSE_REASON_FOR_JOB,
  CANDIDATE_TAGS,
  MANAGE_USER_FIELDS,
  REJECTED_REASONS,
  OFFICE_API,
  DEPARTMENT_API,
  OFFER_TEMPLATE,
  JOB_OPENINGS,
  JOB_BOARDS,
  SINGLE_JOB_OPENING_INFO,
  OFFER_DETAILS,
  EFFICIENCY_REPORTS,
  PIPELINE_REPORTS,
  JOB_CANDIDATE,
  OVERVIEW_SAVED_REPORTS,
  JOB_DASHBOARD,
  ACTIVITY_FEED,
  OFFER_HIRING,
  DASHBOARD,
  SCORE_CARD_DETAILS,
  NOTIFICATIONS,
  ESSENTIAL_REPORTS,
  PERSONALIZED_DASHBOARD,
  PIPE_LINE_REPORTS,
  INTERVIEWING_ACTIVITY,
  DEPARTMENT_SUMMARY,
  APPLICATION_OVER_TIME,
  CANDIDATE_SOURCE,
  USER_API,
  NOTIFICATIONS_BY_USER,
  EMAIL_TEMPLATES,
  NOTIFICATIONS_ACCOUNT,
  JOB_ACTIVITY_FEED,
];
export const generateTags = (result: any, TAG: string) => {
  return result
    ? [
        ...result.map(({ _id }: any) => ({
          type: TAG,
          id: _id,
        })),
        { type: TAG, id: "LIST" },
      ]
    : [{ type: TAG, id: "LIST" }];
};

export const generateSingleTag = (result: any, TAG: string) => {
  return result
    ? [
        {
          type: TAG,
          id: result._id,
        },
      ]
    : [{ type: TAG, id: "LIST" }];
};
