import {
  // AgenciesIcon,
  // BulkImportIcon,
  CustomOptionsIcon,
  // DevCenterIcon,
  EmailTemplatesIcon,
  JobBoardsIcon,
  NotificationIcon,
  OfferTemplatesIcon,
  // OrderHistoryIcon,
  OrganizationIcon,
  // SocialTemplatesIcon,
  UserIcon,
} from "@assets/configuration-dashboard";

export const ConfigurationDashboardData = [
  {
    id: 1,
    title: "Organization",
    Image: OrganizationIcon,
    link: "/configuration/organization",
    description: "View or edit your organization’s details",
  },
  {
    id: 2,
    title: "User",
    Image: UserIcon,
    link: "/configuration/user",
    description: "Manage your team member, or invite new users",
  },
  {
    id: 3,
    title: "Notification",
    Image: NotificationIcon,
    link: "/configuration/notification",
    description: "Configure your notifications",
  },
  {
    id: 4,
    title: "Email Templates",
    Image: EmailTemplatesIcon,
    link: "/configuration/email-templates",
    description: "Configure your Email Templates",
  },
  // {
  //   id: 5,
  //   title: "Social Templates",
  //   Image: SocialTemplatesIcon,
  //   link: "/configuration/social-templates",
  //   description: "Configure your Social Media Templates",
  // },
  {
    id: 6,
    title: "Offer Templates",
    Image: OfferTemplatesIcon,
    link: "/configuration/offer-templates",
    description: "Configure Offer Templates for your entire organization",
  },
  // {
  //   id: 7,
  //   title: "Order History",
  //   Image: OrderHistoryIcon,
  //   link: "/configuration/order-history",
  //   description: "View your order history",
  // },
  {
    id: 8,
    title: "Job Boards",
    Image: JobBoardsIcon,
    link: "/configuration/job-boards",
    description: "Manage your Job Boards on job posts",
  },
  {
    id: 9,
    title: "Custom Options",
    Image: CustomOptionsIcon,
    link: "/configuration/custom-options",
    description: "Manage custom tags, sources, rejection reasons and referrers",
  },
  // {
  //   id: 10,
  //   title: "Agencies",
  //   Image: AgenciesIcon,
  //   link: "/configuration/agencies",
  //   description: "Manage your team member, or invite new users",
  // },
  // {
  //   id: 11,
  //   title: "Dev Center",
  //   Image: DevCenterIcon,
  //   link: "/configuration/dev-center",
  //   description: "Manage your team member, or invite new users",
  // },
  // {
  //   id: 12,
  //   title: "Bulk Import",
  //   Image: BulkImportIcon,
  //   link: "/configuration/bulk-import",
  //   description: "Manage your team member, or invite new users",
  // },
];
