import type { DepartmentFilters } from "./compensation-bands.types";

export const departmentFilters: DepartmentFilters[] = [
    {
        id: 1,
        label: "All",
    },
    {
        id: 2,
        label: "Business Analysis",
    },
    {
        id: 3,
        label: "Finance",
    },
    {
        id: 4,
        label: "Project Management",
    },
    {
        id: 5,
        label: "Customer Success",
    },
    {
        id: 6,
        label: "Development",
    },
    {
        id: 7,
        label: "Human Resources",
    },
];

export const data = [
    {
        id: "1",
        band: "CS Mid",
        department: "Customer Success",
        jobLevel: "Mid",
        tile: "CS Associate",
        location: "London",
        minBasePay: "£60,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "2",
        band: "Dev Jr",
        department: "Development",
        jobLevel: "Junior",
        tile: "Front end Developer",
        location: "London",
        minBasePay: "£40,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "3",
        band: "Dev Mid",
        department: "Development",
        jobLevel: "Mid",
        tile: "Software Engineer",
        location: "London",
        minBasePay: "£60,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "4",
        band: "Dev Sr",
        department: "Development",
        jobLevel: "Senior",
        tile: "Front end Developer",
        location: "London",
        minBasePay: "£100,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "5",
        band: "BA Sr",
        department: "Business Analysis",
        jobLevel: "Senior",
        tile: "Business Analysis",
        location: "London",
        minBasePay: "£100,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "6",
        band: "Finance Sr",
        department: "Finance",
        jobLevel: "Senior",
        tile: "Finance",
        location: "London",
        minBasePay: "£100,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "7",
        band: "PM Sr",
        department: "Project Management",
        jobLevel: "Senior",
        tile: "Project Management",
        location: "London",
        minBasePay: "£100,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
    {
        id: "8",
        band: "Hr Jr",
        department: "Human Resources",
        jobLevel: "Junior",
        tile: "Human Resources",
        location: "London",
        minBasePay: "£40,000",
        midBasePay: "--",
        maxBasePay: "--",
        minVariablePay: "--",
        midVariablePay: "--",
        maxVariablePay: "--",
    },
];