export const defaultValues = {
  firstName: "",
  lastName: "",
  pronouns: [],
  email: "",
  contactNumber: "",
  dob: new Date,
  gender: "",
  ethnicity: "",
  maritalStatus: "",
  about: "",
  address: {
    addressLine: "",
    country: "",
    city: "",
    state: "",
    zipCode: "",
  },
  employeeId: "",
  workEmail: "",
  employmentStartDate: "",
  timeZone: "",
  employeeTitle: "",
  department: "",
  managerId: "",
  location: "",
  employmentStatus: "",
  jobLevel: "",
  emergencyContact: {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    relationship: "",
  },
  attributeOptionIds: {
    age: [],
    experience: [],
  },
};

export const pronounOptions = [
  { id: "she", name: "she" },
  { id: "he", name: "he" },
  { id: "they", name: "they" },
  { id: "you", name: "you" },
  { id: "it", name: "it" },
  { id: "we", name: "we" },
];
